### PR TITLE
TableKit v3

### PR DESCRIPTION
**Pull request by SimeonC**
* Trash old folders, setup new system with rush to potentially replace lerna. Port over existing styles from temp settings work.

### CODE REVIEW

**Comment by gazpachu** [comment]
I think we could merge this PR into a feature branch called `next`, so we have a base. Then it will be easier to make changes. Like, we have to add `npm install -g @microsoft/rush` to the install instructions in the readme

**Comment by SimeonC** [comment]
> I think we could merge this PR into a feature branch called `next`, so we have a base. Then it will be easier to make changes. Like, we have to add `npm install -g @microsoft/rush` to the install instructions in the readme

I did mention in slack - this isn't ready for anyone else to work on as it's not even really working for me. (Hence draft).

This PR is the `next` branch, once it's ready for people to help out/contribute I'll convert the branch to have proper branch protection so we can PR against it.

**Comment by SimeonC** [comment]
Made some updates to this branch, I've left a TODO list in the README for now.

Reason I picked rush is nicely summed up in this article;
https://blog.bitsrc.io/11-tools-to-build-a-monorepo-in-2021-7ce904821cc2

Basically;
* It's fairly straightforward and pretty close to lerna
* It doesn't have all the extra fluff that others have for their requirements (like server/ui monorepos or special uploads/action names which caused more confusion)
* Downside is that whatever package we move to will require a fair bit of work getting the scripts package to run again with it. The build-lib is fairly painless to fix as it's a 1 liner (noted in README, not done) but the others may take a lot more work.
* Release process will have to change as no package managers do what lerna used to do with conventional commits and require a manual changelog process. This has it's advantages as the changelog notes become part of the PR file review and not semi-invisible in the commits tab. Disadvantage is of course that we have some duplication between commits and the changelog. Haven't actually tested if the release system would work for us either.

## Further implementation notes
* It may be easier to not use our scripts directly for this package and just ship ESM files only via TSC build - this would need testing and checking of the output files. (I think it's safe to drop ES5 for Tablekit)
* The commit hooks need some improvement, commitlint might be easier to remove as Rush doesn't use them and the lint-staged via `tablecheck-scripts precommit` needs to use rush to run (probably similar to the prettier docs on their site)

**Comment by gazpachu** [comment]
@SimeonC It seems that Lerna is still going to be maintained: https://github.com/lerna/lerna/issues/3121

If that's the case, I'd prefer to stick with it, so we can focus our time on the main priorities, which is to release the new lightweight components to support our products.

**Comment by SimeonC** [comment]
That's nice, less tooling updates. I'll rename the next branch to `abandoned-rush-tk-3` and close this PR.

**Comment by gazpachu** [comment]
Thank you for your time investigating rush 🙇

**Review by Scamreno — COMMENTED** [review]
Thanks

**Pull request closed without merging**
