### PR TITLE
fix: storybook icon config

### LINKED ISSUE #5: Storybook examples with icons are broken
Any story for a component that uses `tablekit-icon` is failing due to an error while configuring icons

image

### PR DESCRIPTION
**Pull request by wahidmagdy**
- remove '@tablecheck/tablekit-free-icon-config' import from
`preview.tsx`

- add '@tablecheck/tablekit-free-icon-config' imports to all
stories that include icons

Fixes #5

### CODE REVIEW

**Comment by wahidmagdy** [comment]
I'm sure there's a more general solution than importing the config for every story file, however i haven't yet found it and decided to at least do this as a stop-gap measure

**Review by SimeonC — APPROVED** [review]

**Comment by SimeonC** [comment]
Ah, sorry. Forgot to document what the "Labels" need to be in the `CONTRIBUTING.md` file. Can you add a description from here: https://github.com/tablecheck/tablekit/blob/debd282c6dec35f73a38d05913c305c954079d33/.github/workflows/label_checker.yml#L19-L20

**Review by SimeonC — CHANGES_REQUESTED** [review]
Sorry, should have read properly. The commit message for this should be `docs: ...` not `fix: ...` as it doesn't affect the components themselves. The label can be "Internal"

**Comment by wahidmagdy** [comment]
Passed the label checker. are these the correct labels?

**Review by SimeonC — APPROVED** [review]

**Review by SashaShostyr — APPROVED** [review]

**Pull request merged**
