### PR TITLE
Tomb component docs

### PR DESCRIPTION
**Pull request by xsanctom**
docs: added amazing component documentation templates

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @tablecheck/tablekit-css@2.0.1-canary.132.3157635950.0
  npm install @tablecheck/tablekit-react-select@2.0.1-canary.132.3157635950.0
  npm install @tablecheck/tablekit-react@2.0.1-canary.132.3157635950.0
  # or 
  yarn add @tablecheck/tablekit-css@2.0.1-canary.132.3157635950.0
  yarn add @tablecheck/tablekit-react-select@2.0.1-canary.132.3157635950.0
  yarn add @tablecheck/tablekit-react@2.0.1-canary.132.3157635950.0
  ```
</details>

### CODE REVIEW

**Comment by SimeonC** [comment]
I think I prefer us to use more real code examples rather than images, or embedded SVGs for the case where we want some measurements.

**Comment by gazpachu** [comment]
I agree with Simeon's opinion, but I think we can merge this for now, so we can have a base to work on those improvements.

Also, I'd prefer if we move the `Components` to the `Dev` section. @xsanctom if you want I can do that and also squash the commits. ok?

**Comment by SimeonC** [comment]
I think once we've squashed the commits/pushed a new commit we should get the preview deploy to review. Originally this was targeting `main` not `next` which is why I think it didn't trigger.

**Comment by gazpachu** [comment]
@SimeonC where do you suggest uploading the images (the ones with the measurements)?

**Comment by SimeonC** [comment]
TBH I've not got any good ideas around that. I've seen all sorts of things from using imgur or other free hosting sites, uploading into a github comment then using the CDN link that it resolves to. Maybe @DragonStuff has some good ideas? I kinda want that image CMS we talked about ages ago, just something that would allow us to have a S3 bucket/cdn-ish for these kind of images. (both for TK and also for our other projects like website/diner app etc)

**Pull request closed without merging**
