### PR TITLE
fix(tablekit-alert): icon error

### PR DESCRIPTION
**Pull request by gazpachu**
Completes 68

### CODE REVIEW

**Review by SimeonC — APPROVED** [review]

**Review by SimeonC — CHANGES_REQUESTED** [review]
Isn't the error mentioned in #68 to do with the story not having `import '@tablecheck/tablekit-free-icon-config';` like the error suggests? The dev dependency should be the icon config, not the font awesome icons.

https://github.com/tablecheck/tablekit/blob/9063f9f00b1c02ad527e89d79ede87053e09ea0a/packages/password-field/src/PasswordField.stories.tsx#L2

**Comment by gazpachu** [comment]
> Isn't the error mentioned in #68 to do with the story not having `import '@tablecheck/tablekit-free-icon-config';` like the error suggests? The dev dependency should be the icon config, not the font awesome icons.
> 
> https://github.com/tablecheck/tablekit/blob/9063f9f00b1c02ad527e89d79ede87053e09ea0a/packages/password-field/src/PasswordField.stories.tsx#L2

The error is actually triggering in the new diner portal. It happened after I upgraded to tablekit-alert 3.0.0: https://diner-app-spa-staging.tablecheck.com/

**Comment by SimeonC** [comment]
Check you haven't got duplicate versions of the icon-config installed in npm, that's often the cause - `npm ls '@tablecheck/tablekit-pro-icon-config'` or it might be the icon package.

This error is almost always caused by the code where it occurs, either as the error suggests, the import has been forgotten, or there are clashing versions of the config being required due to incomplete dependency upgrade.

**Comment by gazpachu** [comment]
> Check you haven't got duplicate versions of the icon-config installed in npm, that's often the cause - `npm ls '@tablecheck/tablekit-pro-icon-config'` or it might be the icon package.
> 
> This error is almost always caused by the code where it occurs, either as the error suggests, the import has been forgotten, or there are clashing versions of the config/icon packages being required.

Hmm, I've updated all TK packages and now it seems to be fine. Closing ticket. Thanks!

**Pull request closed without merging**
