### PR TITLE
fix(tablekit-alert): close button aria-label

### PR DESCRIPTION
**Pull request by gazpachu**
Completes 63

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @tablecheck/tablekit-alert@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-avatar@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-badge@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-banner@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-button-group@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-button@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-calendar@2.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-checkbox@1.1.1-canary.64.1458672514.0
  npm install @tablecheck/tablekit-enzyme@1.0.2-canary.64.1458672514.0
  npm install @tablecheck/tablekit-free-icon-config@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-icon@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-inline-dialog@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-input-button@1.0.5-canary.64.1458672514.0
  npm install @tablecheck/tablekit-input@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-item@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-language-selector@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-logo@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-modal-dialog@2.0.2-canary.64.1458672514.0
  npm install @tablecheck/tablekit-panel@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-password-field@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-phone-input@2.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-pro-icon-config@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-radio@1.1.2-canary.64.1458672514.0
  npm install @tablecheck/tablekit-select@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-sidenav@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-spinner@1.0.2-canary.64.1458672514.0
  npm install @tablecheck/tablekit-table@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-tabs@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-tag@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-textarea@1.0.4-canary.64.1458672514.0
  npm install @tablecheck/tablekit-theme@1.0.2-canary.64.1458672514.0
  npm install @tablecheck/tablekit-toggle@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-tooltip@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-topnav@1.0.3-canary.64.1458672514.0
  npm install @tablecheck/tablekit-typography@1.0.2-canary.64.1458672514.0
  # or 
  yarn add @tablecheck/tablekit-alert@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-avatar@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-badge@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-banner@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-button-group@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-button@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-calendar@2.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-checkbox@1.1.1-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-enzyme@1.0.2-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-free-icon-config@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-icon@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-inline-dialog@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-input-button@1.0.5-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-input@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-item@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-language-selector@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-logo@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-modal-dialog@2.0.2-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-panel@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-password-field@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-phone-input@2.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-pro-icon-config@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-radio@1.1.2-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-select@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-sidenav@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-spinner@1.0.2-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-table@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-tabs@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-tag@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-textarea@1.0.4-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-theme@1.0.2-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-toggle@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-tooltip@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-topnav@1.0.3-canary.64.1458672514.0
  yarn add @tablecheck/tablekit-typography@1.0.2-canary.64.1458672514.0
  ```
</details>

### CODE REVIEW

**Review by wahidmagdy — APPROVED** [review]

**Comment by wahidmagdy** [comment]
i think this addresses https://github.com/tablecheck/tablekit/issues/63 ? issue 62 seems to be something different

**Review by staevs — APPROVED** [review]

**Comment by gazpachu** [comment]
> i think this addresses #63 ? issue 62 seems to be something different

Thx, fixed

**Review by wahidmagdy — APPROVED** [review]

**Review by SimeonC — APPROVED** [review]

**Comment by gazpachu** [comment]
@SimeonC something went wrong during the release action: https://github.com/tablecheck/tablekit/runs/4206787481?check_suite_focus=true

**Comment by SimeonC** [comment]
I'll look into it, looks like the previous publish failed too so I'll have to mess with npm to fix this.

**Comment by SimeonC** [comment]
Should be fixed now. Had to break the PR - master commit link though so the notification won't be posted here. New alert version is 3.0.0

**Pull request merged**
