### PR TITLE
fix(tablekit-theme): support better extension and overriding of theme colors

### PR DESCRIPTION
**Pull request by SimeonC**
Usage from survey that didn't work;

```ts
declare module '@tablecheck/tablekit-theme' {
  export interface ThemeColors { // note that BaseColors here doesn't work either
    shadowBackground: string;
  }
}

export const customTheme: Partial<Theme> = {
  colors: {
    shadowBackground: 'rgba(0, 0, 0, 0.08)',
    ...CLASSIC_COLORS
  }
};
```

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @tablecheck/tablekit-alert@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-avatar@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-badge@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-banner@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-button-group@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-button@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-calendar@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-checkbox@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-enzyme@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-free-icon-config@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-icon@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-inline-dialog@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-input-button@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-input@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-item@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-language-selector@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-logo@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-modal-dialog@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-panel@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-password-field@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-phone-input@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-pro-icon-config@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-radio@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-select@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-sidenav@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-spinner@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-table@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-tabs@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-tag@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-textarea@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-theme@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-toggle@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-tooltip@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-topnav@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  npm install @tablecheck/tablekit-typography@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  # or 
  yarn add @tablecheck/tablekit-alert@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-avatar@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-badge@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-banner@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-button-group@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-button@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-calendar@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-checkbox@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-enzyme@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-free-icon-config@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-icon@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-inline-dialog@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-input-button@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-input@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-item@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-language-selector@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-logo@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-modal-dialog@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-panel@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-password-field@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-phone-input@2.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-pro-icon-config@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-radio@1.0.3-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-select@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-sidenav@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-spinner@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-table@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-tabs@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-tag@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-textarea@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-theme@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-toggle@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-tooltip@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-topnav@1.0.2-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  yarn add @tablecheck/tablekit-typography@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0
  ```
</details>

### CODE REVIEW

**Comment by wahidmagdy** [comment]
I'm a bit lost about how this works. So they needed to add a prop to the theme, but couldn't modify the theme directly. Then the solution was just to add an extra empty interface in the theming process?

**Comment by SimeonC** [comment]
This is to do with modifying colors, which is a sub-property of Theme, so when I tried to extend BaseColors it didn't merge the values in the theme but overwrote them completely. By extending it as an empty interface and then using module declare on the extension, not the base, this correctly merges the values together rather than overwriting one or the other. `declare module` works rather specially, in fact, if we only need to add a new value to the theme, or completely overwrite a key on the theme that works fine, it's just the case of extending the base colours that doesn't.

**Review by staevs — APPROVED** [review]

**Comment by staevs** [comment]
Actually with previous version I was just able to extend BaseColors like: 
```
declare module '@tablecheck/tablekit-theme' {
  export interface BaseColors {
     hoveredTableRow: string;
  }
```

Actually only naming is a bit awkward here

**Comment by SimeonC** [comment]
Yea, for me it was the `...CLASSIC_COLORS` part that was failing with `BaseColors` extension - though either way, this does make the naming a bit more sensible and it should help catch a lot more weird edge cases without breaking the old way I think.

Could you guys double check in your projects if this breaks anything? `npm install --legacy-peer-deps @tablecheck/tablekit-theme@1.0.1-canary.54.a16a692db53cb7af4642715c0ef34e4bef913d83.0`

**Comment by staevs** [comment]
I've changed my declaration to:
```typescript
declare module '@tablecheck/tablekit-theme' {
  export interface ThemeColors {
    hoveredTableRow: string;
    selectorDisabledOptionColor: string;
    // ...other project specific colors
  }
```
Seems to work fine, it picks up both: tablekit and custom colors

**Review by staevs — APPROVED** [review]

**Review by wahidmagdy — APPROVED** [review]

**Pull request merged**
